'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const D=require('../src/data'),E=require('../src/engine');
const memory=value=>({getItem:()=>JSON.stringify(value),setItem(){}});
const fresh=()=>E.readSave(memory({}));
const character=D.characters.find(c=>c.id==='canero');
assert.equal(D.characters.length,12);assert.equal(character.name,'CAÑERO');assert.equal(character.kind,'companion');assert.equal(character.instrument,null);assert.equal(character.unlockLevel,2);
const save=fresh(),g=new E.Game({progress:save});
g.start(1);assert.equal(D.isCharacterUnlocked(character,save),false,'Entrar en el nivel 2 no concede el personaje');assert.equal(g.toggleCharacter('canero'),false);
g.start(0);g.performance.allowedCharacters.slice(0,5).forEach(id=>g.toggleCharacter(id));g.begin();g.fail('prueba');assert.equal(save.characterUnlocks.includes('canero'),false);
assert.ok(E.recordCompletion(save,0,3000,2));assert.deepEqual(save.characterUnlocks,['canero']);assert.equal(D.isCharacterUnlocked(character,save),true);
let reload=E.readSave(memory(save));assert.deepEqual(E.pendingCharacterRewards(reload).map(c=>c.id),['canero']);E.ackCharacterReward(reload,'canero');reload=E.readSave(memory(reload));assert.equal(E.pendingCharacterRewards(reload).length,0);E.recordCompletion(reload,0,3100,3);assert.equal(E.pendingCharacterRewards(reload).length,0);
const previous=E.readSave(memory({version:4,campaignId:D.campaignId,unlocked:1,stars:[2],best:[3100],characterUnlocks:[],characterRewardsSeen:[],volume:.28}));assert.ok(previous.characterUnlocks.includes('canero'));assert.equal(previous.best[0],3100);assert.equal(previous.volume,.28);assert.deepEqual(E.pendingCharacterRewards(previous).map(c=>c.id),['canero']);
for(const event of D.events){const game=new E.Game({progress:reload});game.start(1);game.performance.eventId=event.id;game.performance.event=event;D.refreshPerformanceAvailability(game.performance,reload);assert.ok(game.toggleCharacter('canero'));if(event.id==='evento-benefico'){assert.equal(game.toggleCharacter('guitarra'),false);assert.equal(game.performance.restrictionReasons.guitarra,'Pone una escusa para no actuar');}game.performance.allowedCharacters.filter(id=>id!=='canero').slice(0,4).forEach(id=>assert.ok(game.toggleCharacter(id)));assert.equal(game.toggleCharacter('coki'),false);assert.ok(game.begin());game.collectorCharacter='canero';const act=game.performance;assert.ok(game.items.every(i=>!['canero','companion','cerveza'].includes(i.type)));game.items.forEach(i=>i.collected=true);game.startRhythm();for(const note of game.notes){game.tick(.001,{},note.at);game.hit(note.lane);}game.tick(.001,{},60);assert.ok(['result','victory'].includes(game.phase));assert.strictEqual(game.performance,act);assert.ok(act.selectedCharacters.includes('canero'));assert.equal(act.selectedCharacters.length,5);}
const root=path.join(__dirname,'..'),manifest=JSON.parse(fs.readFileSync(path.join(root,'docs/canero/protected-before.json'),'utf8').replace(/^\uFEFF/,''));for(const file of manifest){const actual=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file.path))).digest('hex').toUpperCase();assert.equal(actual,file.sha256,'Se modificó un recurso protegido: '+file.path);}
console.log('PASS CAÑERO: bloqueo, victoria, migración, tarjeta única, selección, siete eventos, actuación completa y recursos protegidos intactos');
