'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const D=require('../src/data'),E=require('../src/engine'),R=require('../src/recordings');
const root=path.join(__dirname,'..'),report=path.join(root,'docs/clavelitos-mp3');
let passed=0;function test(name,fn){fn();passed++;console.log('PASS',name);}
test('Audio exacto y original sin modificar',()=>{const c=R.get('clavelitos');assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,c.audioFile))).digest('hex'),c.audioSha256);assert.equal(c.playableSeconds,60);assert.equal(c.sourceOffset,.32);});
test('Todos los tiempos proceden de ataques medidos, sin cuadrícula MIDI',()=>{const c=R.get('clavelitos'),analysis=JSON.parse(fs.readFileSync(path.join(report,'analisis.json'),'utf8'));for(const chart of Object.values(c.charts)){assert.ok(chart.notes.every(n=>analysis.onsets.some(o=>Math.abs(o.at-(n.at+c.sourceOffset))<.000002)));assert.ok(chart.notes.every(n=>n.at>=.1&&n.at+.23<c.playableSeconds));for(let i=0;i<60;i+=5)assert.ok(chart.notes.some(n=>n.at>=i&&n.at<i+5));}assert.ok(c.charts.hard.notes.length>c.charts.normal.notes.length*2);assert.ok(c.charts.normal.notes.every(n=>c.charts.hard.notes.some(h=>h.at===n.at)));});
test('Las dos dificultades conservan teclas, duración y ventanas de puntuación',()=>{for(const level of [0,10]){const g=new E.Game();g.start(level);g.performance.allowedCharacters.slice(0,5).forEach(id=>g.toggleCharacter(id));g.begin();g.startRhythm();assert.equal(g.clock,-3);assert.equal(g.duration,60);assert.equal(g.laneCount,D.levels[level].laneCount);const n=g.notes[0];g.tick(.1,{},n.at);g.hit(n.lane);assert.equal(g.hits,1);assert.equal(g.perfects,1);assert.equal(g.score,120);assert.equal(g.clock,n.at);g.tick(.1,{},59.99);assert.equal(g.clock,59.99);}});
test('Las otras 18 actuaciones conservan la fuente MIDI y se adaptan a 60 segundos',()=>{for(const l of D.levels.filter(l=>l.song!=='clavelitos')){const g=new E.Game();g.start(l.id);g.startRhythm();const melody=require('../src/midi').get(l.song).melody;assert.equal(g.notes.length,Math.ceil(l.notes*1.5));assert.ok(g.notes.every(n=>melody.some(m=>m.pitch===n.pitch)));assert.ok(g.notes.at(-1).at>57);assert.equal(g.duration,60);}});
test('Restauración MIDI no borra recursos ni cambia otros temas',()=>{R.registry.clavelitos.enabled=false;try{const g=new E.Game();g.start();g.startRhythm();assert.equal(g.recording,null);assert.equal(g.duration,60);assert.equal(g.notes.length,Math.ceil(D.levels[0].notes*1.5));}finally{R.registry.clavelitos.enabled=true;}});
const manifestPath=path.join(report,'backup/manifest.json');if(fs.existsSync(manifestPath))test('Sprites, MIDI, MP3 y progreso original intactos',()=>{const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8').replace(/^\uFEFF/,''));const allowed=new Set(['index.html','README.md','css\\game.css','src\\engine.js','src\\audio.js','src\\game.js','src\\art.js','tests\\engine.test.cjs','tests\\audio.test.cjs','tests\\browser-integration.html','tests\\progression.test.cjs','tests\\run-publicacion.cjs','MP3\\catalogo.json']);for(const file of manifest){if(allowed.has(file.path))continue;const hash=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file.path))).digest('hex').toUpperCase();assert.equal(hash,file.sha256,file.path);}});else console.log('SKIP: respaldo privado excluido de la publicación.');
console.log(passed+' suites de integridad, mapas, reloj, regresión y reversibilidad superadas.');
