(function(){
  'use strict';
  const $=id=>document.getElementById(id),D=TunaData,E=TunaEngine;
  const qaMode=location.hash==='#qa'&&window.parent!==window,Rankings=TunaRankings;
  let storage;if(qaMode){const memory={};storage={getItem:k=>memory[k]||null,setItem:(k,v)=>{memory[k]=v;}};}else try{storage=window.localStorage;}catch{storage={getItem(){return null;},setItem(){throw new Error('storage unavailable');}};}
  const save=E.readSave(storage),audio=new TunaAudio(save),art=new TunaArt($('game')),homeArt=new TunaArt($('home-art'));
  let rankingState={name:'',receipts:[]};try{rankingState={...rankingState,...JSON.parse(storage.getItem('tuna-ranking-private-v1')||'{}')};}catch{}rankingState.playerId=Rankings.playerId(storage);rankingState.receipts=Array.isArray(rankingState.receipts)?rankingState.receipts.filter(r=>r&&r.id&&r.token):[];
  function saveRankingState(){try{storage.setItem('tuna-ranking-private-v1',JSON.stringify(rankingState));}catch{}}
  let collectorTurn=0;try{collectorTurn=Number(storage.getItem('rondalla-collector-turn-v1'))||0;}catch{}
  const instrumentNames={pandereta:'Pandereta',guitarra:'Guitarra',bandurria:'Bandurria',laud:'Laúd'};
  const characterFunction=c=>c.kind==='companion'?'🍺 Acompañante':c.kind==='dancer'?'🕺 Bailarín':instrumentNames[c.instrument]||c.instrument;
  const itemNames={pandereta:'la pandereta',guitarra:'la guitarra',bandurria:'la bandurria',laud:'el laúd','guitarra-gafas':'la guitarra',flor:'una flor',partitura:'una partitura',grupo:'el grupo',caras:'el equipo'};
  function nextCollector(ids=D.characters.map(c=>c.id)){const pool=ids.length?ids:D.characters.map(c=>c.id);const id=pool[collectorTurn%pool.length];collectorTurn=(collectorTurn+1)%pool.length;try{storage.setItem('rondalla-collector-turn-v1',String(collectorTurn));}catch{}return id;}
  const game=new E.Game({character:save.character,easy:save.easy,progress:save});let last=performance.now(),uiPhase='',uiMode='',lastAnnouncement='',settingsPaused=false,held=new Set(),touch=new Set(),activePointers=new Map(),lastHud=0,activeReward=null,rewardDone=null;
  const keyDirections={ArrowLeft:'left',KeyA:'left',ArrowDown:'down',KeyS:'down',ArrowUp:'up',KeyW:'up',ArrowRight:'right',KeyD:'right'};
  const lanes={left:0,down:1,up:2,right:3};
  const musicReady=TunaMusic.preload();let lastStoredSong=save.lastSong;
  function musicLabel(){const label=save.music?`♫ ${audio.title||'Activa la música'}${audio.ctx?.state==='running'?'':' · toca para escuchar'}`:'♫ Música apagada';if($('music-now')?.textContent!==label)$('music-now').textContent=label;}
  function rhythmButtons(){document.querySelector('.rhythm-controls').innerHTML=D.keys.slice(0,game.config.laneCount).map((key,i)=>`<button data-lane="${i}" style="--lane:${D.laneColors[i]}" aria-label="Nota ${key}">${D.lanes[i]}<small>${key}</small></button>`).join('');}
  function persist(){const okay=E.writeSave(storage,save);lastStoredSong=save.lastSong;$('storage-status').textContent=okay?'Progreso y ajustes guardados en este navegador.':'El navegador no permite guardar. Puedes jugar, pero el progreso se conservará solo durante esta visita.';}
  function announce(text){if(text===lastAnnouncement)return;lastAnnouncement=text;$('live-status').textContent=text;}
  function closeModal(){if($('modal').open)$('modal').close();}
  function showModal(content){closeModal();$('modal').classList.remove('party-dialog','reward-dialog');$('modal-content').innerHTML=content;$('modal').showModal();$('modal-content').querySelector('button:not(:disabled)')?.focus({preventScroll:true});}
  function title(kicker,title){return `<div class="dialog-head"><p class="eyebrow">${kicker}</p></div><h2>${title}</h2>`;}
  function actions(content){return `<div class="dialog-actions">${content}</div>`;}
  function button(action,text,style='primary'){return `<button class="button ${style}" data-action="${action}">${text}</button>`;}
  function showRewards(done=()=>{}) {
    const character=E.pendingCharacterRewards(save)[0];
    if(!character){activeReward=null;rewardDone=null;closeModal();done();return;}
    activeReward=character;rewardDone=done;
    const columns=character.animationColumns||4,icon=character.kind==='companion'?'🍺':character.kind==='dancer'?'🕺':'🎶';
    showModal(`<div class="unlock-card"><div class="reward-sparkles" aria-hidden="true"><i>✦</i><i>♪</i><i>✦</i><i>♫</i></div><p class="eyebrow">🎉 ¡ENHORABUENA!</p><div class="reward-sprite" role="img" aria-label="${character.name} celebra su incorporación" style="--columns:${columns};--frames:${columns};background-image:url('${D.characterAsset(character,true)}')"></div><h2>🔓 ¡HAS DESBLOQUEADO A ${character.name.toUpperCase()}!</h2><p>${icon} ${character.unlockMessage}</p><p class="reward-level">DISPONIBLE DESDE EL NIVEL ${character.unlockLevel}</p>${actions(button('reward-continue','CONTINUAR'))}</div>`);
    $('modal').classList.add('reward-dialog');announce(`Has desbloqueado a ${character.name}. Disponible desde el nivel ${character.unlockLevel}.`);
  }
  function renderMenu(){
    $('characters').innerHTML=D.characters.map(c=>{const unlocked=D.isCharacterUnlocked(c,save);return `<button class="character-card" data-character="${c.id}" aria-pressed="${c.id===save.character}" aria-label="Elegir ${c.name}" ${unlocked?'':'disabled'}><img src="${D.characterAsset(c)}" alt=""><span><strong>${unlocked?'':'🔒 '}${c.name}</strong><small>${unlocked?c.role:`Disponible en nivel ${c.unlockLevel}`}</small></span>${c.id===save.character?'<span class="selected-mark">✓</span>':''}</button>`;}).join('');
    $('levels').innerHTML=D.levels.map(l=>`<button class="level-card" data-level="${l.id}" ${l.id>save.unlocked?'disabled':''}><span class="level-top"><span class="number">${String(l.id+1).padStart(2,'0')}</span><span class="stars">${l.id>save.unlocked?'◇':save.stars[l.id]?'★'.repeat(save.stars[l.id]):'☆ ☆ ☆'}</span></span><strong>${l.short}</strong><small>${l.id>save.unlocked?'Completa la etapa anterior':save.best[l.id]?`${save.best[l.id].toLocaleString('es-ES')} puntos · Repetir`:l.place.split(' · ')[0]}</small></button>`).join('');
    $('play').innerHTML=`${save.unlocked>0&&save.stars[D.levels.length-1]===0?'Continuar la ronda':'Empezar la ronda'} <span>→</span>`;
    $('easy').checked=save.easy;
  }
  function home(){audio.ambient('menu');persist();held.clear();touch.clear();game.phase='menu';closeModal();$('home').hidden=false;$('play-area').hidden=true;$('pause').hidden=true;uiPhase='menu';renderMenu();musicLabel();$('play').focus();showRewards();}
  function start(level){audio.unlock();game.character=save.character;game.easy=save.easy;game.start(level);const recording=TunaRecordings.get(game.config.song);if(recording)audio.prepareRecording(recording).catch(()=>{});game.collectorCharacter=null;held.clear();touch.clear();$('home').hidden=true;$('play-area').hidden=false;$('pause').hidden=false;uiPhase='';sync();window.scrollTo({top:0,behavior:'instant'});}
  function beacons(){
    $('beacons').innerHTML=game.items.map(i=>`<button class="beacon" data-target="${i.id}" style="left:${i.x/9.6}%;top:${(i.y-30)/5.4}%" aria-label="${game.level===1||game.level===4?'Reunir':'Recoger'} ${itemNames[i.type]||i.type} ${i.id+1}"></button>`).join('')+`<button class="beacon stage" data-target="stage" style="left:${game.stage.x/9.6}%;top:${game.stage.y/5.4}%" aria-label="Ir al escenario y tocar"></button>`;
  }
  function selectionCards(){const p=game.performance,selected=new Set(p.selectedCharacters||[]);return `<div class="party-picker"><div class="party-picker-head"><div><p class="eyebrow">ELIGE TU TUNA</p><h3>TUNA: ${selected.size}/5</h3></div><span class="small muted">Escoge cinco componentes</span></div><div class="party-grid">${D.characters.map(c=>{const blocked=p.unavailableCharacters.includes(c.id),picked=selected.has(c.id),reason=blocked?(p.restrictionReasons[c.id]||'No disponible para este evento'):characterFunction(c);return `<button class="party-card${picked?' is-selected':''}${blocked?' is-unavailable':''}" data-character-pick="${c.id}" aria-pressed="${picked}" ${blocked?'disabled':''}><img src="${D.characterAsset(c)}" alt=""><span><strong>${c.name}</strong><small>${reason}</small></span>${picked?'<b class="party-mark">✓</b>':''}</button>`;}).join('')}</div></div>`;}
  function brief(){const l=game.config,p=game.performance;showModal(title(`NUEVO ENCARGO · ETAPA ${String(l.id+1).padStart(2,'0')}`,`${p.event.icon} ${p.event.name} · ${p.location.name}`)+`<div class="gig-card"><p class="eyebrow">📍 ${p.location.name}</p><h3>${p.event.icon} ${p.event.name}</h3><p>${p.event.description}</p><p class="dialog-quote">«${p.event.narrative}»</p><p class="small muted">🎶 ${l.title} · ${l.round===2?'Dificultad difícil':'Dificultad normal'} · 60 segundos</p></div><img class="dialog-photo" src="assets/referencias/${l.photo}.webp" alt="Fotografía original de la Tuna: ${p.location.name}"><p>${p.prepText}</p><p class="dialog-quote">«${l.intro}»</p><section id="ranking-preview" class="ranking-preview" aria-live="polite"><p class="small muted">Consultando las mejores marcas de esta etapa…</p></section>`+actions(button('choose-group','Elegir el grupo →')+button('home','Volver al menú','secondary')));loadRankingPreview(l.id+1);}
  function selectionScreen(){const l=game.config,p=game.performance,ready=game.selectionStatus().valid;showModal(title('ANTES DE SALIR',`${p.event.icon} ${p.event.name} · ${p.location.name}`)+`<div class="gig-card"><p class="eyebrow">📍 ${p.location.name} · 🎶 ${l.title}</p><p>${p.prepText} Escoge a los cinco componentes que llevarán esta actuación.</p></div>${selectionCards()}<p class="small muted">Los componentes seleccionados serán el grupo de esta preparación y actuación. Elige exactamente cinco.</p>`+actions(`<button class="button primary" data-action="begin" ${ready?'':'disabled'}>COMENZAR ACTUACIÓN <span>→</span></button>`+button('back-brief','← Volver al encargo','secondary')));$('modal').classList.add('party-dialog');}
  function rankingRows(rows,mode){if(!rows?.length)return '<p class="small muted">Todavía no hay puntuaciones publicadas. Puedes inaugurar esta clasificación.</p>';return `<ol class="ranking-list">${rows.map((r,i)=>{const accuracy=mode==='general'?Number(r.general_score||0):Number(r.accuracy||0)*100;const metric=mode==='general'?`${Number(r.levels_played||0)}/${D.levels.length} niveles`:`${Number(r.score||0).toLocaleString('es-ES')} pts`;return `<li><b class="ranking-medal">${i===0?'🥇':i===1?'🥈':i===2?'🥉':String(r.rank||i+1)}</b><strong>${Rankings.escapeHtml(r.player_name)}</strong><span>${metric}</span><em>${accuracy.toFixed(mode==='general'?2:0)}%</em></li>`;}).join('')}</ol>`;}
  async function loadRankingPreview(level){const box=$('ranking-preview');if(!box)return;rankingView={mode:'level',level,offset:0};try{const data=await Rankings.list({mode:'level',level,limit:3});if(!box.isConnected)return;box.innerHTML=`<div class="ranking-preview-head"><b>🏆 MEJORES MARCAS · NIVEL ${level}</b><button class="text-button" data-action="leaderboard-level">Ver tabla completa</button></div>${rankingRows(data.rows,'level')}`;}catch{if(box.isConnected)box.innerHTML='<p class="small muted">No se pudo cargar la clasificación. Puedes comenzar la actuación igualmente.</p>';}}
  let rankingView={mode:'level',level:1,offset:0};
  function showRanking(mode='level',level=game.config?.id+1||1,offset=0){rankingView={mode,level,offset};const opts=D.levels.map(l=>`<option value="${l.id+1}" ${l.id+1===level?'selected':''}>${l.id+1}. ${Rankings.escapeHtml(l.title)}</option>`).join('');showModal(title('CLASIFICACIONES',mode==='general'?'La gira completa':`Nivel ${level} · ${Rankings.escapeHtml(D.levels[level-1]?.title||'')}`)+`<div class="ranking-tabs"><button class="button ${mode==='level'?'primary':'secondary'}" data-action="leaderboard-level">Por nivel</button><button class="button ${mode==='general'?'primary':'secondary'}" data-action="leaderboard-general">General</button>${mode==='level'?`<label>Nivel <select id="ranking-level-select">${opts}</select></label>`:''}</div><div id="ranking-table" class="ranking-table" aria-live="polite"><p class="small muted">Cargando puntuaciones…</p></div><p class="small muted">La general suma la mejor precisión de cada nivel y divide entre ${D.levels.length}; los niveles no jugados cuentan como cero. Un identificador local distingue instalaciones, pero no verifica la identidad.</p>`+actions(button('close','Cerrar','secondary')));loadRankingTable();}
  async function loadRankingTable(){const box=$('ranking-table');if(!box)return;try{const data=await Rankings.list({mode:rankingView.mode,level:rankingView.level,limit:20,offset:rankingView.offset});if(!box.isConnected)return;const pageCount=Math.ceil((data.total||0)/20);box.innerHTML=`<p class="small muted">${Number(data.total||0).toLocaleString('es-ES')} resultados · Página ${Math.floor(rankingView.offset/20)+1}${pageCount?` de ${pageCount}`:''}</p>${rankingRows(data.rows,rankingView.mode)}<div class="ranking-pagination">${rankingView.offset?'<button class="button secondary" data-action="leaderboard-prev">← Anterior</button>':''}${rankingView.offset+20<(data.total||0)?'<button class="button secondary" data-action="leaderboard-next">Siguiente →</button>':''}</div>`;}catch(error){if(box.isConnected)box.innerHTML=`<p class="small muted">${Rankings.escapeHtml(error.message)} Puedes seguir jugando mientras el servicio vuelve a estar disponible.</p>`;}}
  function resultCast(){return `<div class="result-cast" aria-label="Los cinco músicos de esta actuación">${game.performance.selectedCharacters.map(id=>{const c=D.characters.find(ch=>ch.id===id);return c?`<div><img src="${D.characterAsset(c)}" alt=""><span>${c.name}</span></div>`:'';}).join('')}</div>`;}
  function refreshRecordingClock(){if(game.recording){audio.update(game);const clock=audio.recordingClock();game.tick(0,{x:0,y:0},clock??game.clock);}}
  function hit(lane){refreshRecordingClock();game.hit(lane);}
  function pauseAudio(){if(game.recording)audio.pauseRecording();else audio.stop();}
  function pause(){refreshRecordingClock();game.pause();held.clear();touch.clear();pauseAudio();sync();}
  function result(){
    const victory=game.phase==='victory',accuracy=game.hits/game.notes.length,stars=accuracy>=.9?3:accuracy>=.72?2:1;
    audio.stop();E.recordCompletion(save,game.level,game.score,stars);persist();
    const levelNumber=game.level+1,bestKey=String(levelNumber);rankingState.personal=rankingState.personal||{};const previous=rankingState.personal[bestKey];if(!previous||game.score>previous.score||(game.score===previous.score&&accuracy>previous.accuracy))rankingState.personal[bestKey]={score:game.score,accuracy,playedAt:new Date().toISOString()};saveRankingState();
    const p=game.performance,receipt=rankingState.receipts.find(r=>r.level===levelNumber);showRewards(()=>{showModal(title(victory?'LA NOCHE ES VUESTRA':'ACTUACIÓN COMPLETADA',victory?'¡Una ronda para recordar!':`${p.event.icon} ${p.event.name} · ${p.location.name}`)+`<div class="gig-card"><p class="eyebrow">📍 ${p.location.name} · ${p.event.name}</p><p>${p.closingText}</p><p class="small muted">🎵 NIVEL ${levelNumber} · ${game.config.title} · ${game.config.round===2?'DIFÍCIL':'NORMAL'}</p></div>${resultCast()}<div class="result-stars" aria-label="${stars} estrellas">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><p>${game.config.after}</p><div class="results-grid"><div><small>PUNTOS</small><b>${game.score.toLocaleString('es-ES')}</b></div><div><small>A COMPÁS</small><b>${Math.round(accuracy*100)}%</b></div><div><small>MEJOR COMBO</small><b>${game.bestCombo}</b></div></div>${previous?`<p class="small muted">Tu mejor marca local en ${game.config.title}: ${previous.score.toLocaleString('es-ES')} puntos · ${Math.round(previous.accuracy*100)}%.</p>`:''}<p class="small muted">Bonificación por llegar a tiempo: ${game.bonus} puntos. Total de esta ronda: ${game.total.toLocaleString('es-ES')} puntos.</p><section class="rank-submit"><h3>🏆 ¿Quieres aparecer en la clasificación?</h3><label for="rank-name">Nombre o apodo público</label><input id="rank-name" maxlength="24" autocomplete="nickname" aria-describedby="rank-privacy"><p id="rank-privacy" class="small muted">El apodo y resultado serán visibles públicamente durante 12 meses. No escribas tu nombre completo, correo ni teléfono. Puedes jugar sin guardarlo.</p><p id="rank-submit-status" class="small muted" aria-live="polite">${receipt?'Ya tienes una marca guardada en esta etapa.':'Guardar es opcional; el récord personal se conserva en este navegador.'}</p><div class="rank-submit-actions"><button class="button primary" data-action="save-ranking">Guardar mi resultado</button>${receipt?button('delete-ranking','Retirar mi resultado','secondary'):''}<button class="button secondary" data-action="continue">Continuar sin guardar</button></div></section>`+actions(victory?button('restart','Siguiente encargo →')+button('home','Inicio','secondary'):button('next','Siguiente actuación →')+button('retry','Repetir','secondary')));const input=$('rank-name');if(input){input.value=rankingState.name||'';input.addEventListener('input',()=>{const cleaned=Rankings.safeName(input.value);if(cleaned)rankingState.name=cleaned;else rankingState.name=input.value.slice(0,24);saveRankingState();});}});
    announce(victory?'Victoria. Has completado la gira.':`Nivel ${levelNumber} superado con ${game.score} puntos.`);
  }
  function sync(){
    if(game.phase!==uiPhase){uiPhase=game.phase;
      if(game.phase==='brief'){beacons();rhythmButtons();brief();}
      if(game.phase==='playing'){closeModal();$('game').focus({preventScroll:true});}
      if(game.phase==='paused')showModal(title('UN MOMENTO PARA AFINAR','La ronda espera')+'<p>La partida está pausada. Los músicos también necesitan tomar aire.</p>'+actions(button('resume','Seguir tocando →')+button('retry','Reiniciar','secondary')+button('home','Inicio','secondary')));
      if(game.phase==='result'||game.phase==='victory')result();
      if(game.phase==='defeat'){audio.stop();showModal(title('VOLVEMOS A ENSAYAR','Esta ronda se nos escapó')+`<p>${game.reason}</p><p class="dialog-quote">${game.mode==='rhythm'?'Mira las notas, no las teclas. Pulsa cuando lleguen a los círculos de la línea dorada.':'Puedes tocar directamente los objetos. Tu músico encontrará un camino por la plaza.'}</p>`+actions(button('retry','Intentarlo de nuevo →')+button('home','Inicio','secondary')));announce('Derrota. Puedes reiniciar esta etapa.');}
    }
    if(game.mode!==uiMode){uiMode=game.mode;held.clear();touch.clear();$('beacons').hidden=game.mode!=='explore';$('explore-controls').hidden=game.mode!=='explore';$('rhythm-controls').hidden=game.mode!=='rhythm';}
  }
  function hud(){if(game.phase==='menu')return;
    $('level-number').textContent=`${String(game.level+1).padStart(2,'0')}`;$('place').textContent=`📍 ${game.performance.location.name} · ${game.performance.event.name}`;$('level-title').textContent=`${game.performance.event.icon} ${game.config.title}`;
    $('score').textContent=game.score.toLocaleString('es-ES');$('health-fill').style.width=`${Math.max(0,game.health)}%`;$('health-fill').style.background=game.health<30?'#db7584':'#98bd98';$('health-label').textContent=game.mode==='rhythm'?'PÚBLICO':'ÁNIMO';
    const seconds=Math.ceil(game.mode==='rhythm'?Math.max(0,game.duration-(game.recording?Math.max(0,game.clock):game.clock)):Math.max(0,game.remaining));$('timer').textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;$('timer-label').textContent=game.mode==='rhythm'?'CANCIÓN':'TIEMPO';
    const count=game.items.filter(i=>i.collected).length;$('progress').textContent=game.mode==='rhythm'?`${game.hits} / ${game.notes.length}`:`${count} / ${game.items.length}`;
    if(game.mode==='rhythm'){const next=game.notes.find(n=>!n.judged);$('next-note').textContent=next?`Próxima nota: ${D.lanes[next.lane]} · ${Math.max(0,next.at-game.clock).toFixed(2)} s`:'¡Último acorde!';}
    $('objective').textContent=game.mode==='rhythm'?`🎶 ${game.performance.location.name} · ${game.performance.event.name}. Teclas ${D.keys.slice(0,game.laneCount).join(" · ")}: pulsa al cruzar la línea dorada. Objetivo: ${Math.round(game.config.threshold*100)}% a compás.`:count===game.items.length?'¡Equipo completo! Ve al escenario y pulsa espacio, o toca el escenario.':`${game.performance.prepText} ${game.config.goal}`;
    game.items.forEach(i=>{const el=$('beacons').querySelector(`[data-target="${i.id}"]`);if(el)el.hidden=i.collected;});
    $('play-area').dataset.phase=game.phase;$('play-area').dataset.mode=game.mode;$('play-area').dataset.collected=count;$('play-area').dataset.health=Math.round(game.health);
  }
  function processEvents(){game.drain().forEach(e=>{
    if(e.type==='load'){art.particles=[];audio.ambient('explore');persist();musicLabel();}
    if(e.type==='resume'&&game.mode==='explore')audio.resumeAmbient();
    if(e.type==='collect'){art.burst(e.item.x,e.item.y-30);audio.effect('collect');announce(`Recogido ${e.item.type}. ${game.items.filter(i=>i.collected).length} de ${game.items.length}.`);}
    if(e.type==='rhythm'){if(game.recording)audio.selectRecording(game.recording);else audio.select(game.config.song,{loop:true,offset:game.musicOffset});if(!qaMode)Rankings.start(game.level,rankingState.playerId).catch(()=>{});musicLabel();announce(`${game.performance.event.name} en ${game.performance.location.name}. ${game.performance.readyText}`);}
    if(['hit','damage','wrong','miss','result','victory','defeat'].includes(e.type)){audio.effect(e.type);if(e.type==='hit'){const el=document.querySelector(`[data-lane="${e.lane}"]`);el?.classList.add('pressed');setTimeout(()=>el?.classList.remove('pressed'),120);art.burst(427+(e.lane+.5)*456/game.laneCount,443,D.laneColors[e.lane]);}if(e.type==='wrong'||e.type==='miss'){const el=document.querySelector(`[data-lane="${e.lane}"]`);el?.classList.add('missed');setTimeout(()=>el?.classList.remove('missed'),180);}}
  });}
  async function saveRankingResult(){const status=$('rank-submit-status'),input=$('rank-name'),buttonEl=$('modal-content').querySelector('[data-action="save-ranking"]'),name=Rankings.safeName(input?.value||'');if(!name){if(status)status.textContent='Escribe un apodo válido de hasta 24 caracteres.';input?.focus();return;}if(buttonEl)buttonEl.disabled=true;if(status)status.textContent='Validando y guardando la marca…';rankingState.name=name;saveRankingState();try{const response=await Rankings.submit({playerName:name,score:game.score,accuracy:game.hits/game.notes.length,hits:game.hits,misses:game.misses,notes:game.notes.length});if(response.receipt){rankingState.receipts=rankingState.receipts.filter(r=>r.level!==response.receipt.level);rankingState.receipts.push(response.receipt);saveRankingState();}if(status)status.textContent=response.improved?'¡Marca guardada! Ya aparece en la clasificación pública.':`Tu mejor marca de esta etapa sigue siendo ${game.score.toLocaleString('es-ES')} puntos.`;if(buttonEl){buttonEl.textContent=response.improved?'Resultado guardado ✓':'Mejor marca ya registrada';buttonEl.disabled=true;}if(response.improved&&!$('modal-content').querySelector('[data-action="delete-ranking"]'))$('modal-content').querySelector('.rank-submit-actions')?.insertAdjacentHTML('beforeend',button('delete-ranking','Retirar mi resultado','secondary'));}catch(error){if(status)status.textContent=error.message||'No se pudo guardar. Tu récord local y la partida siguen disponibles.';if(buttonEl)buttonEl.disabled=false;}}
  async function deleteRankingResult(){const receipt=rankingState.receipts.find(r=>r.level===game.level+1),status=$('rank-submit-status');if(!receipt)return;if(status)status.textContent='Retirando la marca pública…';try{const result=await Rankings.remove(receipt);if(!result.deleted)throw new Error('No se pudo comprobar la retirada con este navegador.');rankingState.receipts=rankingState.receipts.filter(r=>r.level!==receipt.level);saveRankingState();if(status)status.textContent='Resultado retirado de la clasificación pública.';$('modal-content').querySelector('[data-action="delete-ranking"]')?.remove();}catch(error){if(status)status.textContent=error.message||'No se pudo retirar el resultado ahora.';}}
  function onAction(action){
    if(action==='reward-continue'&&activeReward){const done=rewardDone;E.ackCharacterReward(save,activeReward.id);persist();activeReward=null;renderMenu();showRewards(done);return;}
    if(activeReward)return;
    if(action==='save-ranking'){saveRankingResult();return;}
    if(action==='delete-ranking'){deleteRankingResult();return;}
    if(action==='continue'){onAction(game.phase==='victory'?'restart':'next');return;}
    if(action==='leaderboard-level'){showRanking('level',game.phase==='menu'?rankingView.level:game.config.id+1,0);return;}
    if(action==='leaderboard-general'){showRanking('general',1,0);return;}
    if(action==='leaderboard-next'){showRanking(rankingView.mode,rankingView.level,rankingView.offset+20);return;}
    if(action==='leaderboard-prev'){showRanking(rankingView.mode,rankingView.level,Math.max(0,rankingView.offset-20));return;}
    if(action==='choose-group'){selectionScreen();return;}
    if(action==='back-brief'){brief();return;}
    if(action==='begin'){if(game.begin()){game.collectorCharacter=nextCollector(game.performance.selectedCharacters);audio.unlock();}else{selectionScreen();announce(game.selectionStatus().reason);return;}}
    if(action==='home')home();
    if(action==='resume')game.resume();
    if(action==='retry-recording'){audio.selectRecording(game.recording,game.clock);game.resume();uiPhase='';}
    if(action==='retry'){audio.stop();game.retry();game.collectorCharacter=nextCollector(game.performance.selectedCharacters);}
    if(action==='next'){audio.stop();game.next();game.collectorCharacter=nextCollector(game.performance.selectedCharacters);}
    if(action==='restart')start(0);
    if(action==='close')closeModal();
    sync();
  }
  $('modal-content').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)onAction(b.dataset.action);});
  $('modal-content').addEventListener('change',e=>{if(e.target.id==='ranking-level-select')showRanking('level',Number(e.target.value),0);});
  $('modal-content').addEventListener('click',e=>{const b=e.target.closest('[data-character-pick]');if(!b||b.disabled)return;const scroll=$('modal').scrollTop,id=b.dataset.characterPick;game.toggleCharacter(id);selectionScreen();$('modal').scrollTop=scroll;$('modal-content').querySelector(`[data-character-pick="${id}"]`)?.focus({preventScroll:true});});
  $('play').addEventListener('click',()=>start(save.stars[D.levels.length-1]===0?save.unlocked:0));
  $('brand').addEventListener('click',e=>{e.preventDefault();home();});
  $('characters').addEventListener('click',e=>{const b=e.target.closest('[data-character]');if(!b||b.disabled)return;save.character=b.dataset.character;persist();renderMenu();});
  $('levels').addEventListener('click',e=>{const b=e.target.closest('[data-level]');if(b&&!b.disabled)start(Number(b.dataset.level));});
  $('easy').addEventListener('change',()=>{save.easy=$('easy').checked;persist();});
  $('pause').addEventListener('click',()=>{if(game.phase==='playing')pause();else if(game.phase==='paused'){game.resume();sync();}});
  $('interact').addEventListener('click',()=>game.interact());
  $('beacons').addEventListener('click',e=>{const b=e.target.closest('[data-target]');if(!b)return;const target=b.dataset.target==='stage'?'stage':Number(b.dataset.target);const point=target==='stage'?game.stage:game.items[target];game.navigate(point.x,point.y,target);$('game').focus({preventScroll:true});});
  $('game').addEventListener('pointerdown',e=>{if(game.mode!=='explore'||game.phase!=='playing')return;const r=$('game').getBoundingClientRect(),x=(e.clientX-r.left)*960/r.width,y=(e.clientY-r.top)*540/r.height;const item=game.items.find(i=>!i.collected&&Math.hypot(i.x-x,i.y-y)<65);if(item)game.navigate(item.x,item.y,item.id);else if(Math.hypot(game.stage.x-x,game.stage.y-y)<85)game.navigate(game.stage.x,game.stage.y,'stage');else game.navigate(x,y);});
  document.querySelectorAll('[data-direction]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();audio.unlock();b.setPointerCapture(e.pointerId);activePointers.set(e.pointerId,b.dataset.direction);touch.add(b.dataset.direction);});const release=e=>{const d=activePointers.get(e.pointerId);activePointers.delete(e.pointerId);if(d&&!Array.from(activePointers.values()).includes(d))touch.delete(d);};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release);});
  document.querySelector('.rhythm-controls').addEventListener('pointerdown',e=>{const b=e.target.closest('[data-lane]');if(!b)return;e.preventDefault();audio.unlock();hit(Number(b.dataset.lane));});
  document.addEventListener('keydown',e=>{
    if(e.code==='Escape'){if($('settings').open)return;if(game.phase==='playing'){e.preventDefault();pause();}else if(game.phase==='paused'){e.preventDefault();game.resume();sync();}return;}
    if(game.phase!=='playing'||$('settings').open)return;
    if(['INPUT','BUTTON'].includes(e.target.tagName)&&!e.target.closest('.rhythm-controls,.explore-controls'))return;
    if(keyDirections[e.code]){e.preventDefault();if(e.repeat)return;audio.unlock();const d=keyDirections[e.code];if(game.mode==='explore')held.add(d);else hit(lanes[d]);}
    else if(game.mode==='rhythm'&&D.codes.includes(e.code)){e.preventDefault();if(!e.repeat)hit(D.codes.indexOf(e.code));}
    if(e.code==='Space'){e.preventDefault();if(e.repeat)return;if(game.mode==='explore')game.interact();else{refreshRecordingClock();const next=game.notes.filter(n=>!n.judged).sort((a,b)=>Math.abs(a.at-game.clock)-Math.abs(b.at-game.clock))[0];if(next)hit(next.lane);}}
  });
  document.addEventListener('keyup',e=>held.delete(keyDirections[e.code]));
  function unfocus(){held.clear();touch.clear();activePointers.clear();if(game.phase==='playing')pause();}
  window.addEventListener('blur',()=>{held.clear();touch.clear();activePointers.clear();});document.addEventListener('visibilitychange',()=>{if(document.hidden)unfocus();});
  $('modal').addEventListener('cancel',e=>{if(activeReward){e.preventDefault();return;}if(game.phase==='paused'){e.preventDefault();game.resume();sync();}else if(game.phase!=='menu')e.preventDefault();});
  const fullscreenButton=$('fullscreen');
  function syncFullscreen(){const active=Boolean(document.fullscreenElement||document.webkitFullscreenElement);fullscreenButton.classList.toggle('active',active);fullscreenButton.setAttribute('aria-label',active?'Salir de pantalla completa':'Activar pantalla completa');fullscreenButton.title=active?'Salir de pantalla completa':'Activar pantalla completa';const label=fullscreenButton.querySelector('span');if(label)label.textContent=active?'Salir de pantalla completa':'Pantalla completa';}
  async function toggleFullscreen(){try{const active=document.fullscreenElement||document.webkitFullscreenElement;if(active){if(document.exitFullscreen)await document.exitFullscreen();else if(document.webkitExitFullscreen)document.webkitExitFullscreen();}else{const root=document.documentElement;if(root.requestFullscreen)await root.requestFullscreen({navigationUI:'hide'});else if(root.webkitRequestFullscreen)root.webkitRequestFullscreen();else{$('live-status').textContent='La pantalla completa no está disponible en este navegador.';return;}}}catch(error){$('live-status').textContent='No se pudo activar la pantalla completa en este navegador.';}}
  fullscreenButton.addEventListener('click',toggleFullscreen);document.addEventListener('fullscreenchange',syncFullscreen);document.addEventListener('webkitfullscreenchange',syncFullscreen);syncFullscreen();
  $('settings-open').addEventListener('click',()=>{settingsPaused=game.phase==='playing';if(settingsPaused){refreshRecordingClock();game.pause();uiPhase='paused';held.clear();touch.clear();pauseAudio();} $('settings').showModal();});
  document.querySelector('[data-close=settings]').addEventListener('click',()=>$('settings').close());
  $('settings').addEventListener('close',()=>{if(settingsPaused&&game.phase==='paused'){game.resume();uiPhase='';sync();}settingsPaused=false;});
  ['music','effects'].forEach(id=>{$(id).checked=save[id];$(id).addEventListener('change',()=>{save[id]=$(id).checked;if(id==="music"){if(audio.recordingTransport)audio.recordingVolume();else if(!save.music)audio.stop();else if(game.phase==='menu')audio.ambient('menu');else if(game.mode==='explore')audio.ambient('explore');}persist();musicLabel();});});
  $('volume').value=Math.round(save.volume*100);$('volume-value').textContent=`${Math.round(save.volume*100)}%`;$('volume').addEventListener('input',()=>{save.volume=Number($('volume').value)/100;$('volume-value').textContent=`${$('volume').value}%`;audio.volume();persist();});
  $('test-sound').addEventListener('click',async()=>{await audio.unlock();audio.strum();audio.effect('collect');$('audio-status').textContent=audio.available?'Sonido preparado. Música y efectos respetan tus ajustes.':'Este navegador no ha podido activar el audio. La partida puede continuar en silencio.';});
  $('how-open').addEventListener('click',()=>showModal(title('ANTES DE SALIR','Dos formas de llevar la ronda')+`<p><b>En la plaza:</b> reúne lo que necesita el grupo. Usa WASD o las flechas y recoge con espacio. Con ratón o pantalla táctil, toca un objeto para caminar hasta él y recogerlo. Los bancos bloquean el paso y los charcos móviles te quitan ánimo.</p><p><b>En la actuación:</b> pulsa ←, ↓, ↑ o → cuando la nota alcance la línea dorada. Empieza con A y S; se añaden W, D, J y K. Las cuatro primeras también admiten flechas. Toca los botones musicales en pantalla. Espacio toca la nota más cercana: una alternativa de un solo botón.</p><p>Acumula combos para sumar más puntos. Necesitas entre el 50% y el 60% de aciertos, según la etapa. Si se agota el tiempo o el ánimo, puedes repetir la etapa. Escape pausa la partida.</p><p class="small muted">«Ritmo tranquilo» amplía el margen para acertar y reduce el daño. Tus mejores marcas y niveles se guardan en este navegador.</p>`+actions(button('close','Entendido →'))));
  $('rankings-open').addEventListener('click',()=>showRanking('general',1,0));
  $('credits-open').addEventListener('click',()=>showModal(title('HECHO CON LOS NUESTROS','Una Tuna con identidad')+`<p>Una aventura original inspirada en la Rondalla de Lopera: beca roja, traje negro, instrumentos de cuerda y noches de actuaciones. Escudo y fotografías proceden de esta web.</p><div class="credits-cast">${D.characters.map(c=>`<div><img src="${D.characterAsset(c)}" alt="Diseño canónico de ${c.name}"><strong>${c.name}</strong><p>${c.detail}</p><img class="reference" src="${c.referencePath}" alt="Fotografía usada como referencia visual"></div>`).join('')}</div><p class="small">Las ilustraciones son interpretaciones de rasgos visibles, con nombres de instrumento. Las escenas y diálogos del juego son ficción. Efectos, escenarios y sprites pixel art creados para este juego. Referencia del reparto: imagen aportada en PERSONAJES. Los diez arreglos base se repiten en una segunda ronda con más densidad; Cartagenera sigue una melodía instrumental inspirada en la referencia de Tuna de Botín.</p><p class="small">Fuentes musicales: <a href="https://tablatunas.com/terminos-servicio/" target="_blank" rel="noopener">Tablatunas / Soplas</a> (<a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">arreglos CC BY 4.0</a>), <a href="https://partiturak.eus/ver/El%20rey" target="_blank" rel="noopener">Partiturak</a> y <a href="https://www.tunaespana.es/?p=3420" target="_blank" rel="noopener">Tuna España</a>. Adaptación: fragmentos, tempo, timbres y acompañamiento. Detalle de fuentes y derechos en assets/audio/FUENTES.md.</p><p class="small">Referencia de experiencia: <a href="https://isabel-arrans.itch.io/novatuno" target="_blank" rel="noopener">Novatuno, de Isabel Arrans ↗</a>. Se han consultado su página y sus diarios de desarrollo; no se han reutilizado recursos, código, textos ni música.</p>`+actions(button('close','Volver a la ronda →'))));
  // A secondary broken image never removes the game or a dialog.
  document.addEventListener('error',e=>{if(e.target.tagName==='IMG'){e.target.style.visibility='hidden';e.target.setAttribute('aria-hidden','true');}},true);
  audio.ambient('menu');renderMenu();persist();musicLabel();showRewards();
  document.addEventListener('pointerdown',()=>{audio.unlock().then(musicLabel);},{capture:true});
  document.addEventListener('keydown',()=>{audio.unlock().then(musicLabel);},{capture:true});
  $('music-now').addEventListener('click',async()=>{await audio.unlock();musicLabel();});
  $('next-song').addEventListener('click',async()=>{audio.ambient('menu');persist();await audio.unlock();musicLabel();});
  // Deterministic integration driver is available only inside the test iframe.
  // It exercises the real controller, audio, HUD, dialogs and renderer.
  let qaRenderClock=0;
  if(qaMode)window.TunaQA={game,save,audio,art,storage,start,musicReady,
    step(dt,input={x:0,y:0},audioClock=null){if(game.recording){processEvents();audio.update(game);game.tick(dt,input,Number.isFinite(audioClock)?audioClock:(audio.recordingClock()??game.clock));}else game.tick(dt,input);processEvents();audio.update(game);sync();qaRenderClock+=dt;if(qaRenderClock>=.1||dt===0||game.phase!=='playing'){if(game.phase==='menu')homeArt.render(null,qaRenderClock);else art.render(game,qaRenderClock);hud();qaRenderClock=0;}},
    stats(){return game.stats();}
  };
  function frame(now){
    const raw=(now-last)/1000;last=now;const dt=Math.min(raw,.1);
    // Large gaps are clamped; visibilitychange already pauses real tab switches.
    // A slow frame or a browser screenshot must not open the pause dialog.
    if(game.phase==='menu'){homeArt.render(null,dt);audio.update(game);musicLabel();}
    else{
      const input={x:Number(held.has('right')||touch.has('right'))-Number(held.has('left')||touch.has('left')),y:Number(held.has('down')||touch.has('down'))-Number(held.has('up')||touch.has('up'))};
      // Catch up through small collision steps when a frame arrives late.
      // Music and the timer follow elapsed time instead of the frame count.
      if(game.recording){
        processEvents();audio.update(game);
        const transport=audio.recordingTransport;
        if(transport?.status==='error'&&game.phase==='playing'){game.pause();uiPhase='paused';showModal(title('LA GRABACIÓN NO ESTÁ LISTA','Vamos a recuperar el sonido')+`<p>${transport.error}</p>`+actions(button('retry-recording','Reintentar grabación →')+button('home','Inicio','secondary')));}
        else if(transport?.status==='playing'&&audio.ctx?.state!=='running'&&game.phase==='playing')pause();
        game.tick(dt,input,audio.recordingClock()??game.clock);
      }else{
        let elapsed=Math.min(raw,1);
        while(elapsed>0&&game.phase==='playing'){const step=Math.min(.05,elapsed);game.tick(step,input);elapsed-=step;}
      }
      processEvents();audio.update(game);sync();art.render(game,dt);if(now-lastHud>80){hud();lastHud=now;}
    }
    if(save.lastSong!==lastStoredSong)persist();
    requestAnimationFrame(frame);
  }
  if(qaMode){let running=false;window.TunaQA.run=()=>{if(!running){running=true;last=performance.now();requestAnimationFrame(frame);}};}
  else requestAnimationFrame(frame);
})();
